baseURL = "http://example.org/"
languageCode = "en-us"
title = "Tracking DDR ECC issues on a standalone app"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
